### ISSUE TITLE
All settings of nyc and mocha?

### ISSUE THREAD

**Issue by laggingreflex** [laggingreflex/mochista#13]
Mochista currently doesn't use **all** of nyc/istanbul's and mocha's settings. I did initially aim to support them all so that it could be used as a replacement for both, but my own use cases were simple enough and I only implemented the settings I was using. 

I hadn't even checked whether there would be clashes between their settings and mochista's own (if any). I also implemented a setting `--all` in mochista that had different purpose in nyc/mocha (issues pointed out in https://github.com/laggingreflex/mochista/issues/2, fixed in https://github.com/laggingreflex/mochista/commit/7f8900d8adb732f1062a8c2fd37b5fb9853ff3bd https://github.com/laggingreflex/mochista/commit/a2db9f29833b4859fde68fc6d56c60d3799bfd83). 

So currently it doesn't support **all** nyc/mochista's settings, but I definitely plan to add them. PRs most welcome!

**Comment by laggingreflex** [comment]
It also doesn't parse nyc settings from package.json. I've implemented it in this pr: https://github.com/laggingreflex/mochista/pull/14 but I'm not sure now if mixing settings from nyc and mocha would be a good idea. For instance the "reporter" setting mean different things in both - in nyc it's coverage report format (lcov/text), whereas in mocha it's the test reporter (spec). In mochista the "reporter" setting is for mocha's test reporter whereas for nyc/istanbul's coverage report the setting is just "report". 

Then there's "extensions" setting in nyc, which I'm not sure how to make it play well with --test-files and --source-files which have values with extensions already included, like "{src,lib}/**/*.{js,coffee}". 

So I think mochista as such can't fully be a replacement for both. 

One idea is to prefix --nyc-reporter or --mocha-reporter to each setting.

**Comment by davidlaym** [comment]
I'm facing the same issue with `--all` `--opts` and `--extension` when trying to replace my mocha+nyc config for a typescript project (with a mocha.opts file in the root). The support for both mocha and nyc is there but can't make it work on mochista.

**Comment by laggingreflex** [comment]
I've completely re-written this. 

The goal is now no longer to support **all** mocha and nyc flags, and especially not to be a drop-in replacement for both. It wasn't a wise decision to begin with in hindsight since there would've been a lot of flags/feature collisions.

Anyways it does support `--all` and `--extensions` now. Here's a typescript project I've tested this on: https://github.com/laggingreflex/typescript-react-library. Please see the npm script "mochista" and all the flags it uses to make it work. 

`--opts` is also no longer supported. It does support `.env` file (via [dotenv]) and all can take all command-line flags from it (via [yargs' .env][yargs-env] feature)

[dotenv]: https://github.com/motdotla/dotenv
[yargs-env]: https://github.com/yargs/yargs/blob/master/docs/api.md#envprefix

Currently I've only implemented the flags/features I use the most. But I'll keep on adding as I find more use cases. PRs are always welcome!

I'm considering this solved but please feel free to reopen if you find issues or have any questions.
