### ISSUE TITLE
No coverage report generated

### ISSUE THREAD

**Issue by pke** [laggingreflex/mochista#17]
With this line as script `mochista -w --live-server` the coverage dir is created but empty (except a hidden .tmp dir). The live server installs with progress but does not seem to mount (on as SSH shell).

**Comment by laggingreflex** [comment]
Fixed. Please try v0.22.0

**Comment by pke** [comment]
Thanks for a quick fix. Did you forget to publish the package?

**Comment by pke** [comment]
Fetched it from GH and a report is generated now. Live server does not work though. On each first run its getting reinstalled and never mounts on port 8080 on the ssh machine.

Care to eloberate what was the cause of the reports not being generated? I saw you basically just updated packages to new major/minor versions. Was this something that broke in a minor version update of one of the dependencies?
Maybe you should lock the dependencies to a specific version without using version ranges. Not every package owner knows how to semver.

**Comment by laggingreflex** [comment]
[This](https://github.com/laggingreflex/mochista/commit/6216ff3c5e8cd3a5e35fddc9ae3cfc9ee012d386#diff-20accb9553a9a9a2b271dfe4dbcad7f5R14) was the cause, c8's API had changed. Not sure what version it changed in. 

>Not every package owner knows how to semver.

Definitely agree, I've seen this far too often. Maybe I'll just introduce package-lock.json

**Comment by laggingreflex** [comment]
Live server works for me. Live server is installed using npx. If I remember, the re-installation was an issue with npx, make sure you're on latest npm.

**Comment by laggingreflex** [comment]
Ah, I see the reinstall issue as well now. [This](https://github.com/zkat/npx/issues/113) was the npx issue I remembered, not sure the current status of it. I thought they fixed it. 

I'm thinking of removing live server feature altogether. I think the user would be better off managing live server stuff themselves.

**Comment by pke** [comment]
Yeah I'd opt to remove it and instead just put up instructions how to set it up, if one needs it.
