### ISSUE TITLE
Add support for nyc --all flag

### ISSUE THREAD

**Issue by tonywoode** [laggingreflex/mochista#2]
[nyc has the following flag](https://www.npmjs.com/package/nyc#include-reports-for-files-that-are-not-required)
however mochista has its own [--all flag](https://www.npmjs.com/package/mochista#usage), which has unrelated functionality
Are you planning to support the nyc --all flag?

**Comment by laggingreflex** [comment]
I might, but it's not a priority for me personally at the moment so I'll have to postpone it to the future. PR welcome though. 

Right now the way it works is that it registers a require hook (hooks into all require calls) and thus it can only know about the files that are actually required. (related code: https://github.com/laggingreflex/mochista/blob/master/src/istanbul/instrument/index.js#L19)

Such a functionality will need to re-write whatever nyc does to include all files that aren't required by the testing (mocha) code.

**Comment by garex** [comment]
Currently `nyc` has `--all` flag in package.json, but as I understand, mochista not used any `nyc` settings.

Sad, but this is show stopper for me.

**Comment by laggingreflex** [comment]
Added. https://github.com/laggingreflex/mochista/commit/a2db9f29833b4859fde68fc6d56c60d3799bfd83 https://github.com/laggingreflex/mochista/commit/7f8900d8adb732f1062a8c2fd37b5fb9853ff3bd Released 0.12.2. Please check it out and let me know.

**Comment by garex** [comment]
@laggingreflex tnx!
